import React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within } from "storybook/test";
import DueDatesPage from "@/pages/DueDatesPage";
import ActionsPage from "@/pages/ActionsPage";
import { route } from "../../../mock/runtime/registry";
import { getDb } from "../../../mock/runtime/db";

const meta = { title: "Surfaces/Actions", component: DueDatesPage, tags:["viewport:1280x720","viewport:1440x900"], parameters:{pulse:{route:"/due-dates",scenario:"v0/actions/action-required",persona:"LEGAL_COUNSEL"}} } satisfies Meta<typeof DueDatesPage>;
export default meta;
type Story = StoryObj<typeof meta>;
const full=["viewport:1366x768","viewport:1920x1080","viewport:640x360@2"];
const ready=async(canvasElement:HTMLElement)=>{const c=within(canvasElement);await expect(await c.findByRole("heading",{name:"Patent event instructions"},{timeout:15000})).toBeVisible();await expect(await c.findByRole("heading",{name:"Response to examination report"},{timeout:15000})).toBeVisible();return c;};
const ops=(slug:string,persona="PHOTON_ADMIN")=>({render:()=> <ActionsPage/>,parameters:{pulse:{route:"/actions",scenario:`v0/actions/${slug}`,persona}}});
export const WorkspaceAdminActionRequired: Story = { tags:full, play:async({canvasElement})=>{const c=await ready(canvasElement);await expect(await c.findByLabelText(/Respond to the office action/)).toBeEnabled();await expect(c.getByRole("button",{name:"Review instruction to send"})).toBeDisabled();} };
export const WorkspaceAdminSavedDraft: Story = { parameters:{pulse:{scenario:"v0/actions/saved-draft"}},play:async({canvasElement})=>{const c=await ready(canvasElement);await expect(await c.findByLabelText(/Respond to the office action/)).toBeChecked();await expect(c.getByRole("heading",{name:"Draft saved"})).toBeVisible();} };
export const WorkspaceAdminSubmitted: Story = { parameters:{pulse:{scenario:"v0/actions/submitted"}},play:async({canvasElement})=>{const c=await ready(canvasElement);await expect(c.getByRole("heading",{name:"Submitted",exact:true})).toBeVisible();} };
export const WorkspaceAdminUpdated: Story = { parameters:{pulse:{scenario:"v0/actions/updated"}} };
export const WorkspaceAdminNoAction: Story = { parameters:{pulse:{scenario:"v0/actions/no-action"}} };
export const PhotonAcknowledged: Story = { ...ops("acknowledged"),tags:full };
export const PhotonInProgress: Story = { ...ops("in-progress") };
export const PhotonCompleted: Story = { ...ops("completed") };
export const PhotonDeclined: Story = { ...ops("declined") };
export const PhotonOverdue: Story = { ...ops("overdue") };
export const MissingTemplate: Story = { parameters:{pulse:{scenario:"v0/actions/missing-template"}},play:async({canvasElement})=>{const c=await ready(canvasElement);await expect(await c.findByRole("heading",{name:"Instruction options are not configured"})).toBeVisible();} };
export const SubmissionError: Story = { tags:["viewport:640x360@2"],play:async({canvasElement})=>{const c=await ready(canvasElement);await userEvent.click(await c.findByLabelText(/Respond to the office action/));await userEvent.click(c.getByRole("button",{name:"Review instruction to send"}));getDb().flags.mutationsFail=true;await userEvent.click(c.getByRole("button",{name:"Send instruction",exact:true}));await expect(await c.findByRole("alert")).toHaveTextContent("Your choices are retained");getDb().flags.mutationsFail=false;} };
export const Loading: Story = { parameters:{msw:{handlers:[route("get","/v1/due-dates",async()=>{await new Promise(r=>setTimeout(r,60000));return {data:[]};})]}},play:async({canvasElement})=>{await expect(await within(canvasElement).findByRole("status")).toHaveTextContent("Loading events");} };
export const InventorRefused: Story = { render:()=> <ActionsPage/>,parameters:{pulse:{route:"/actions",scenario:"v0/inventor/portfolio",persona:"INVENTOR"}} };
export const CaseOwnerIncoming: Story = { ...ops("submitted","CASE_OWNER"),tags:full };
export const PhotonEmpty: Story = { ...ops("empty-queue") };
export const ManyRequests: Story = { ...ops("many","CASE_OWNER") };
export const Countries: Story = { tags:["viewport:640x360@2"],parameters:{pulse:{scenario:"v0/actions/countries"}},play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByLabelText(/File in selected countries/,{},{timeout:15000}));await userEvent.click(c.getByLabelText("United States",{exact:true}));await userEvent.click(c.getByLabelText("India",{exact:true}));await expect(c.getByRole("button",{name:"Review instruction to send"})).toBeEnabled();} };
export const LongTitle: Story = { ...ops("long-title","CASE_OWNER"),tags:["viewport:640x360@2"] };
export const Confirmation: Story = { tags:["viewport:640x360@2"],play:async({canvasElement})=>{const c=await ready(canvasElement);await userEvent.click(await c.findByLabelText(/Respond to the office action/));await userEvent.click(c.getByRole("button",{name:"Review instruction to send"}));await expect(c.getByRole("button",{name:"Send instruction",exact:true})).toBeVisible();} };
export const DeclineResponse: Story = { ...ops("submitted","CASE_OWNER"),tags:["viewport:640x360@2"],play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"More"},{timeout:15000}));await userEvent.click(await within(document.body).findByRole("menuitem",{name:"Decline request…"}));await userEvent.type(c.getByLabelText("Why is Photon Legal declining this request?"),"The supporting record needs clarification before work can proceed.");await expect(c.getByRole("button",{name:"Decline request",exact:true})).toBeEnabled();} };
export const LoadError: Story = { parameters:{msw:{handlers:[route("get","/v1/due-dates",()=>({status:503,body:{message:"Unavailable"}}))]}},play:async({canvasElement})=>{await expect(await within(canvasElement).findByRole("heading",{name:"Actions could not be loaded"},{timeout:15000})).toBeVisible();} };
