import React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within } from "storybook/test";
import ClientsPage from "@/pages/client/ClientsPage";
import ClientDetailPage from "@/pages/client/ClientDetailPage";
import { route } from "../../../mock/runtime/registry";
const meta = { title:"Surfaces/Clients and onboarding", component:ClientsPage, tags:["redesign","viewport:1280x720","viewport:1440x900"], parameters:{pulse:{route:"/clients",scenario:"v0/clients/ready",persona:"PHOTON_ADMIN"}} } satisfies Meta<typeof ClientsPage>;
export default meta;
type Story = StoryObj<typeof meta>;
const detail=(slug:string,persona="PHOTON_ADMIN") => ({render:()=> <ClientDetailPage/>,parameters:{pulse:{scenario:`v0/clients/${slug}`,persona,path:"/clients/:clientId",route:(db:any)=>`/clients/${db.clients.find((c:any)=>c.domain?.includes("northwind") || c.name.startsWith("Northwind")).id}?tab=overview`}}});
const check=(heading:string)=>async({canvasElement}:{canvasElement:HTMLElement})=>{await expect(await within(canvasElement).findByRole("heading",{name:heading},{timeout:15000})).toBeVisible();};
const allWidths=["viewport:1366x768","viewport:1920x1080","viewport:640x360@2"];
export const PhotonAdmin:Story={tags:allWidths,play:async({canvasElement})=>{await expect(await within(canvasElement).findByRole("region",{name:"Selected client brief"},{timeout:15000})).toBeVisible();}};
export const CaseOwner:Story={tags:allWidths,parameters:{pulse:{persona:"CASE_OWNER"}}};
export const PotentialClient:Story={...detail("potential-client"),play:check("Configure the allowed domain")};
export const NewClient:Story={play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"Create client",exact:true}));await expect(await within(document.body).findByRole("dialog")).toHaveTextContent("Create a client workspace");}};
export const NoOwner:Story={...detail("no-owner"),play:check("Assign a Case Owner")};
export const NoAdmin:Story={...detail("no-admin"),play:check("Invite the first Workspace Admin")};
export const NoInventors:Story={...detail("no-inventors"),play:check("Set up inventor invitations")};
export const NoPortfolio:Story={...detail("no-portfolio"),play:check("Import the initial patent portfolio")};
export const ImportInProgress:Story={...detail("import-in-progress"),play:check("Patent import in progress")};
export const ImportErrors:Story={...detail("import-errors"),play:check("Correct the patent import")};
export const Ready:Story={...detail("ready"),tags:allWidths,play:check("Ready for client support")};
export const ReadyCaseOwner:Story={...detail("ready","CASE_OWNER"),tags:allWidths,play:check("Ready for client support")};
export const Disabled:Story={...detail("disabled"),play:check("Client is inactive")};
export const AccessRequest:Story={...detail("access-request","CASE_OWNER"),play:async({canvasElement})=>{await expect(await within(canvasElement).findByRole("button",{name:"Request client access"},{timeout:15000})).toBeVisible();}};
export const Loading:Story={parameters:{msw:{handlers:[route("get","/v1/clients",async()=>{await new Promise(r=>setTimeout(r,60000));return {};})]}},play:async({canvasElement})=>{await expect(await within(canvasElement).findByRole("status")).toHaveTextContent("Loading client workspaces");}};
export const Error:Story={parameters:{msw:{handlers:[route("get","/v1/clients",()=>({status:503,body:{message:"Unavailable"}}))]}},play:check("Clients could not be loaded")};
export const Empty:Story={parameters:{pulse:{scenario:"v0/clients/empty",persona:"CASE_OWNER"}},play:check("No clients assigned yet")};
export const LongTitle:Story={...detail("long-title"),tags:["viewport:640x360@2"]};
export const InviteAdmin:Story={...detail("no-admin"),play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click((await c.findAllByRole("button",{name:"Invite Workspace Admin",exact:true}))[0]);await expect(await within(document.body).findByRole("dialog")).toHaveTextContent("Email address");}};
export const InviteLink:Story={...detail("no-inventors"),play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"Set up invitations"}));await expect(await within(document.body).findByRole("dialog")).toHaveTextContent("No active invitation link");}};
export const ImportResult:Story={...detail("import-errors"),play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"Review import result"}));await expect(await within(document.body).findByRole("dialog")).toHaveTextContent("Rows to correct in the latest import");}};
export const ConfirmReadiness:Story={...detail("confirm-ready"),play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"Review readiness"}));await expect(await within(document.body).findByRole("dialog")).toHaveTextContent("Confirm onboarding readiness");}};
export const EditDomain:Story={...detail("potential-client"),play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"Configure domain"}));await expect(c.getByRole("textbox",{name:"Allowed domain"})).toBeVisible();}};
export const SaveFailed:Story={...detail("potential-client"),parameters:{...detail("potential-client").parameters,msw:{handlers:[route("patch","/v1/clients/:id",()=>({status:503,body:{message:"Client information could not be saved. Your changes are still here."}}))]}},play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"Configure domain"}));await userEvent.type(c.getByRole("textbox",{name:"Allowed domain"}),"northwind.test");await userEvent.click(c.getByRole("button",{name:"Save client",exact:true}));await expect(await c.findByRole("alert")).toHaveTextContent("Your changes are still here");await expect(c.getByRole("textbox",{name:"Allowed domain"})).toHaveValue("northwind.test");}};
export const ClientSupport:Story={...detail("ready"),play:async({canvasElement})=>{const c=within(canvasElement);await check("Ready for client support")({canvasElement});await userEvent.click(c.getByText("Ideas, portfolio and upcoming work",{exact:true}));c.getByRole("link",{name:"Open approved ideas"}).scrollIntoView();await expect(c.getByRole("heading",{name:"Upcoming Actions and dates"})).toBeVisible();}};
export const ClientSettings:Story={...detail("ready"),play:async({canvasElement})=>{const c=within(canvasElement);await check("Ready for client support")({canvasElement});await userEvent.click(c.getByText("Client information and settings",{exact:true}));c.getByLabelText("Client relationship").scrollIntoView();await expect(c.getByRole("button",{name:"Mark client inactive"})).toBeVisible();}};
export const SharedInvitation:Story={...detail("ready"),play:async({canvasElement})=>{const c=within(canvasElement);await check("Ready for client support")({canvasElement});await userEvent.click(c.getByText(/^People and invitations/));await userEvent.click(c.getByRole("button",{name:"Inventor invitation link",exact:true}));await expect(await within(document.body).findByRole("dialog")).toHaveTextContent("Copy invite link");}};
export const OwnerAssignment:Story={...detail("no-owner"),play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(await c.findByRole("button",{name:"Assign Case Owner",exact:true}));await expect(await within(document.body).findByRole("dialog")).toHaveTextContent("Jonas Weber");}};
