import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within } from "storybook/test";
import { useLocation } from "react-router-dom";
import IdeaDetailsPage from "@/pages/IdeaDetailsPage";
import IdeaDraftPage from "@/pages/IdeaDraftPage";
import type { Db } from "../../../mock/runtime/types";
import { route } from "../../../mock/runtime/registry";
const DetailRoute = () => useLocation().pathname.endsWith("/draft") ? <IdeaDraftPage /> : <IdeaDetailsPage />;
const meta = { title: "Surfaces/Idea detail and status", component: DetailRoute,
  beforeEach: () => { for (const key of Object.keys(sessionStorage)) if (key.startsWith("pulse-disclosure:")) sessionStorage.removeItem(key); },
  tags: ["redesign", "viewport:1280x720", "viewport:1440x900"],
  parameters: { pulse: { scenario: "v0/idea-detail/submitted", persona: "INVENTOR", path: "/ideas/:id/*", route: (db: Db) => `/ideas/${db.ideas[0].id}` } },
} satisfies Meta<typeof DetailRoute>;
export default meta;
type Story = StoryObj<typeof meta>;
const state = (slug: string, persona = "INVENTOR") => ({ pulse: { scenario: `v0/idea-detail/${slug}`, persona } });
const seen = (name: string) => async ({ canvasElement }: { canvasElement: HTMLElement }) => { const c = within(canvasElement); await expect(await c.findByRole("heading", { name, exact: true }, { timeout: 15000 })).toBeVisible(); };
const detail = async (canvasElement: HTMLElement) => { const c = within(canvasElement); await c.findByRole("heading", { name: "Invention brief" }); await expect(c.getByText(/Full disclosure · revision/).closest("details")).not.toHaveAttribute("open"); await expect(c.queryByRole("button", { name: "Evaluate idea" })).toBeNull(); return c; };
export const Draft: Story = { parameters: state("draft"), play: seen("Start from what you already have") };
export const Evaluated: Story = { parameters: state("evaluated"), play: seen("Submission readiness") };
export const Submitted: Story = { tags: ["viewport:1366x768", "viewport:1920x1080", "viewport:640x360@2"], play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByRole("heading", { name: "Awaiting Workspace Admin review" })).toBeVisible(); await expect(c.queryByRole("button", { name: "Send to Photon Legal" })).toBeNull(); } };
export const UnderReview: Story = { tags: ["viewport:1366x768", "viewport:1920x1080", "viewport:640x360@2"], parameters: state("under-review", "LEGAL_COUNSEL"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByRole("button", { name: "Send to Photon Legal" })).toBeEnabled(); await expect(c.getByRole("button", { name: "Request changes" })).toBeEnabled(); } };
export const ChangesRequested: Story = { parameters: state("changes-requested"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(await c.findByRole("heading", { name: "Review feedback" })).toBeVisible(); await expect(c.getByRole("button", { name: "Update disclosure" })).toBeEnabled(); } };
export const Rejected: Story = { parameters: state("rejected"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByRole("button", { name: "Revise and resubmit" })).toBeEnabled(); } };
export const Resubmitted: Story = { parameters: state("resubmitted"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByText("Full disclosure · revision 2")).toBeVisible(); } };
export const SentToPhoton: Story = { tags: ["viewport:1366x768", "viewport:1920x1080", "viewport:640x360@2"], parameters: state("sent-to-photon", "CASE_OWNER"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByRole("button", { name: "Record filing" })).toBeEnabled(); } };
export const Filed: Story = { parameters: state("filed"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByRole("button", { name: "View patent" })).toBeEnabled(); } };
export const Granted: Story = { parameters: state("granted"), play: seen("Granted") };
export const Closed: Story = { parameters: state("closed"), play: seen("Closed") };
export const MissingEvaluation: Story = { parameters: state("missing-evaluation"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByText("No evaluation is available. This disclosure can be reviewed on its own merits.")).toBeVisible(); } };
export const PartialEvaluation: Story = { parameters: state("partial-evaluation"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByText("Partial result · the score is provisional")).toBeVisible(); } };
export const OnBehalfAttribution: Story = { parameters: state("on-behalf-attribution", "LEGAL_COUNSEL"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByText("Submitted by")).toBeVisible(); await expect(c.getByText("Co-inventors")).toBeVisible(); } };
export const Loading: Story = { parameters: { msw: { handlers: [route("get", "/v1/ideas/:id", async () => { await new Promise((r) => setTimeout(r, 12000)); return { status: 503, body: { message: "Unavailable" } }; })] } }, play: async ({ canvasElement }) => { await expect(await within(canvasElement).findByText("Loading idea…")).toBeVisible(); } };
export const Error: Story = { parameters: { msw: { handlers: [route("get", "/v1/ideas/:id", () => ({ status: 503, body: { message: "Idea unavailable" } }))] } }, play: seen("This idea is unavailable") };
export const PermissionDenied: Story = { parameters: { pulse: { scenario: "v0/inventor/portfolio", route: (db: Db) => `/ideas/${db.ideas.find((idea) => idea.author_id !== db.users.find((u) => u.email === "inventor@northwind.test")?.id && !db.inventors.some((credit) => credit.idea_id === idea.id && credit.inventor_id === db.users.find((u) => u.email === "inventor@northwind.test")?.id))?.id}` } }, play: seen("This idea is unavailable") };
export const PhotonAdmin: Story = { tags: ["viewport:1366x768", "viewport:1920x1080", "viewport:640x360@2"], parameters: state("sent-to-photon", "PHOTON_ADMIN"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await expect(c.getByRole("button", { name: "Record filing" })).toBeEnabled(); } };
export const LongContent: Story = { tags: ["viewport:640x360@2"], parameters: state("long-content", "LEGAL_COUNSEL"), play: async ({ canvasElement }) => { await detail(canvasElement); } };
export const DecisionReason: Story = { parameters: state("under-review", "LEGAL_COUNSEL"), play: async ({ canvasElement }) => { const c = await detail(canvasElement); await userEvent.click(c.getByRole("button", { name: "Request changes" })); const d = within(await within(document.body).findByRole("dialog")); await expect(d.getByRole("button", { name: "Request changes" })).toBeDisabled(); await userEvent.type(d.getByLabelText("Your reason (required)"), "Please document the load-response measurement."); await expect(d.getByRole("button", { name: "Request changes" })).toBeEnabled(); } };

export const AttachmentFailure: Story = { parameters: { msw: { handlers: [route("get", "/v1/files/:id/raw", () => ({ status: 503, body: { message: "Attachment unavailable" } }))] } }, play: async ({ canvasElement }) => { const c = await detail(canvasElement); await userEvent.click(c.getByText(/Source material and attachments ·/)); await userEvent.click(c.getByRole("button", { name: "Download", exact: true })); await expect(await c.findByText("Could not download this attachment. Try downloading it again.")).toBeVisible(); } };
export const DecisionFailure: Story = { parameters: { ...state("under-review", "LEGAL_COUNSEL"), msw: { handlers: [route("post", "/v1/ideas/:id/review", () => ({ status: 503, body: { message: "Decision unavailable" } }))] } }, play: async ({ canvasElement }) => { const c = await detail(canvasElement); await userEvent.click(c.getByRole("button", { name: "Request changes" })); const d = within(await within(document.body).findByRole("dialog")); await userEvent.type(d.getByLabelText("Your reason (required)"), "Please document the load-response measurement."); await userEvent.click(d.getByRole("button", { name: "Request changes" })); await expect(await d.findByText("Could not save this decision. Your note remains here; try again.")).toBeVisible(); await expect(d.getByLabelText("Your reason (required)")).toHaveValue("Please document the load-response measurement."); } };
