import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within, waitFor } from "storybook/test";
import PatentsPage from "@/pages/PatentsPage";
import { NORTHWIND } from "../../../mock/scenarios/v0/personas";
import { getDb } from "../../../mock/runtime/db";
import { route } from "../../../mock/runtime/registry";
const meta = { title: "Surfaces/Patent portfolio", component: PatentsPage,
  tags: ["redesign", "viewport:1280x720", "viewport:1440x900"],
  parameters: { pulse: { scenario: "v0/inventor/portfolio", persona: "INVENTOR", route: "/patents" } },
} satisfies Meta<typeof PatentsPage>;
export default meta;
type Story = StoryObj<typeof meta>;
const viewports = ["viewport:1366x768", "viewport:1920x1080", "viewport:640x360@2"];
const ready = async (canvasElement: HTMLElement) => { const c = within(canvasElement); await waitFor(() => expect(c.getAllByRole("link").filter(link => link.getAttribute("href")?.startsWith("/patents/")).length).toBeGreaterThan(0), { timeout: 15000 }); return c; };
export const Inventor: Story = { tags: viewports, play: async ({ canvasElement }) => { const c = await ready(canvasElement); await expect(c.queryByRole("button", { name: "Import patents" })).not.toBeInTheDocument(); await expect(c.queryByText(/Next date/)).not.toBeInTheDocument(); } };
export const WorkspaceAdmin: Story = { tags: viewports, parameters: { pulse: { scenario: "v0/workspace-admin/queue", persona: "LEGAL_COUNSEL" } }, play: async ({ canvasElement }) => { const c = await ready(canvasElement); await expect(c.queryByRole("button", { name: "Import patents" })).not.toBeInTheDocument(); } };
export const CaseOwner: Story = { tags: viewports, parameters: { pulse: { scenario: "v0/case-owner/my-work", persona: "CASE_OWNER" } }, play: async ({ canvasElement }) => { const c = await ready(canvasElement); await expect(c.getByRole("button", { name: "Import patents" })).toBeVisible(); } };
export const PhotonAdmin: Story = { tags: viewports, parameters: { pulse: { scenario: "v0/photon-admin/firm", persona: "PHOTON_ADMIN" } }, play: CaseOwner.play };
export const EmptyImportedPortfolio: Story = { parameters: { pulse: { scenario: "v0/workspace-admin/empty-portfolio", persona: "LEGAL_COUNSEL" } }, play: async ({ canvasElement }) => { await expect(await within(canvasElement).findByRole("heading", { name: "No patents have been added" }, { timeout: 15000 })).toBeVisible(); } };
export const ThousandsOfRecords: Story = { parameters: { pulse: { scenario: "v0/shape/large", persona: "LEGAL_COUNSEL" } }, play: async ({ canvasElement }) => { const c = await ready(canvasElement); await expect(await c.findByText(/14,356 patents/)).toBeVisible(); } };
export const LongTitles: Story = { parameters: { pulse: { scenario: "v0/portfolio/long-titles" } }, play: async ({ canvasElement }) => { const c = await ready(canvasElement); await userEvent.type(c.getByRole("textbox", { name: "Title or application number" }), "Self-tensioning"); await userEvent.click(c.getByRole("button", { name: "Search patents" })); await expect(await c.findByText("12 matching patents")).toBeVisible(); } };
export const MultipleJurisdictions: Story = { parameters: { pulse: { route: "/patents?jurisdiction=US" } }, play: async ({ canvasElement }) => { const c = await ready(canvasElement); await expect(c.getByRole("combobox", { name: "Jurisdiction" })).toHaveValue("US"); await waitFor(() => { const cells = canvasElement.querySelectorAll("tbody tr td:nth-child(3)"); expect(cells.length).toBeGreaterThan(0); for (const cell of cells) expect(cell).toHaveTextContent("United States"); }); } };
export const FilteredEmpty: Story = { parameters: { pulse: { route: "/patents?search=unmatched-synthetic-record" } }, play: async ({ canvasElement }) => { await expect(await within(canvasElement).findByRole("heading", { name: "No patents match these filters" }, { timeout: 15000 })).toBeVisible(); } };
export const ImportResult: Story = { parameters: { pulse: { scenario: "v0/portfolio/import-result", persona: "CASE_OWNER" } }, play: async ({ canvasElement }) => { const c = await ready(canvasElement); await userEvent.click(c.getByRole("button", { name: "Import patents" })); const d = within(await within(document.body).findByRole("dialog")); const client = d.getByRole("combobox", { name: "Import client" }) as HTMLSelectElement; await waitFor(() => expect(client.options.length).toBeGreaterThan(1)); await userEvent.selectOptions(client, client.options[1].value); await userEvent.upload(d.getByLabelText("Portfolio file"), new File(["application_number,title\nSYN-0001,Synthetic mechanism"], "synthetic-portfolio.csv", { type: "text/csv" })); await userEvent.click(d.getByRole("button", { name: "Import portfolio" })); await expect(await d.findByText("Imported with rows to review", {}, { timeout: 15000 })).toBeVisible(); } };
export const Loading: Story = { parameters: { msw: { handlers: [route("get", "/v1/patents", async () => { await new Promise(resolve => setTimeout(resolve,60000)); return []; })] } }, play: async ({ canvasElement }) => { await expect(await within(canvasElement).findByText("Loading patents…")).toBeVisible(); } };
export const Error: Story = { parameters: { msw: { handlers: [route("get", "/v1/patents", () => ({ status: 503, body: { message: "Patents unavailable" } }))] } }, play: async ({ canvasElement }) => { const c = within(canvasElement); await expect(await c.findByRole("heading", { name: "Patents could not be loaded" }, { timeout: 15000 })).toBeVisible(); await expect(c.getByRole("button", { name: "Reload patents" })).toBeEnabled(); } };

export const ImportFailure: Story = { parameters: { pulse: { scenario: "v0/shape/failure", persona: "CASE_OWNER" } }, play: async ({ canvasElement }) => {
  const c = await ready(canvasElement); await userEvent.click(c.getByRole("button", { name: "Import patents" })); const d = within(await within(document.body).findByRole("dialog")); const client = d.getByRole("combobox", { name: "Import client" }) as HTMLSelectElement;
  await waitFor(() => expect(client.options.length).toBeGreaterThan(1)); const selected = client.options[1].value; await userEvent.selectOptions(client, selected); await userEvent.upload(d.getByLabelText("Portfolio file"), new File(["application_number,title\nSYN-0001,Synthetic mechanism"], "synthetic-portfolio.csv", { type: "text/csv" })); await userEvent.click(d.getByRole("button", { name: "Import portfolio" })); await expect(await d.findByRole("alert")).toHaveTextContent("Your file and client selection are retained"); await expect(client).toHaveValue(selected); await expect((d.getByLabelText("Portfolio file") as HTMLInputElement).files?.[0]?.name).toBe("synthetic-portfolio.csv"); getDb().flags.mutationsFail = false;
} };
export const ImportInProgress: Story = { parameters: { pulse: { scenario: "v0/portfolio/import-result", persona: "CASE_OWNER" } }, play: async ({ canvasElement }) => {
  const c = await ready(canvasElement); await userEvent.click(c.getByRole("button", { name: "Import patents" })); const d = within(await within(document.body).findByRole("dialog")); const client = d.getByRole("combobox", { name: "Import client" }) as HTMLSelectElement; await waitFor(() => expect(client.options.length).toBeGreaterThan(1)); await userEvent.selectOptions(client, client.options[1].value); await userEvent.upload(d.getByLabelText("Portfolio file"), new File(["application_number,title\nSYN-0001,Synthetic mechanism"], "synthetic-portfolio.csv", { type: "text/csv" })); getDb().flags.latencyMs = 60000; await userEvent.click(d.getByRole("button", { name: "Import portfolio" })); await expect(await d.findByText("Importing portfolio…")).toBeVisible(); await expect(d.getByRole("button", { name: "Cancel" })).toBeDisabled(); await expect(d.getByRole("button", { name: "Import portfolio" })).toBeDisabled();
} };

export const EmptyCaseOwner: Story = { parameters: { pulse: { scenario: "v0/workspace-admin/empty-portfolio", persona: "CASE_OWNER", route: `/patents?client=${NORTHWIND.id}` } }, play: async ({ canvasElement }) => { const c = within(canvasElement); await expect(await c.findByRole("heading", { name: "No patents have been added" }, { timeout: 15000 })).toBeVisible(); await expect(c.getByRole("button", { name: "Import patents" })).toBeVisible(); await expect(c.getByRole("combobox", { name: "Portfolio client" })).toHaveValue(NORTHWIND.id); } };
export const EmptyPhotonAdmin: Story = { parameters: { pulse: { scenario: "v0/workspace-admin/empty-portfolio", persona: "PHOTON_ADMIN", route: `/patents?client=${NORTHWIND.id}` } }, play: EmptyCaseOwner.play };
