import {chromium} from '../../../node_modules/playwright/index.mjs';
import {blockEgress} from '../../../tools/design/lib/serve.mjs';
const b=await chromium.launch(),c=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),p=await c.newPage();await blockEgress(c);let mutations=[];p.on('request',r=>{if(r.method()!=='GET'&&r.url().includes('/v1/actions'))mutations.push([r.method(),r.url(),r.postData()]);});
const read=()=>p.evaluate(async()=>await(await fetch('/v1/actions?limit=100')).json());
try{await p.goto('http://127.0.0.1:3740/due-dates?scenario=v0/actions/action-required&role=LEGAL_COUNSEL');await p.getByRole('heading',{name:'Patent event instructions'}).waitFor();await p.getByLabel(/Respond to the office action/).check();await p.getByLabel('Note to Photon Legal — optional').fill('Synthetic client instruction note.');await p.getByRole('button',{name:'Save draft',exact:true}).click();await p.getByText('Draft saved. Send it when you are ready for Photon Legal to act.',{exact:true}).waitFor();let rows=(await read()).data;if(rows[0].submission_state!=='DRAFT'||rows[0].note!=='Synthetic client instruction note.')throw Error('first draft not persisted');const firstId=rows[0].id;
await p.getByRole('navigation',{name:'Patent events'}).getByRole('button').filter({hasText:'Patent renewal'}).first().click();await p.getByLabel(/Pay the fee/).check();await p.getByRole('button',{name:'Save draft',exact:true}).click();await p.getByText('Draft saved. Send it when you are ready for Photon Legal to act.',{exact:true}).waitFor();rows=(await read()).data;if(rows.filter(r=>r.submission_state==='DRAFT').length!==2)throw Error('second draft not stored');const secondId=rows.find(r=>r.id&&r.id!==firstId).id;
await p.getByRole('navigation',{name:'Patent events'}).getByRole('button').filter({hasText:'Response to examination report'}).first().click();await p.getByRole('button',{name:'Review instruction to send',exact:true}).click();await p.getByRole('button',{name:'Send instruction',exact:true}).click();await p.getByText('Instruction sent to Photon Legal.',{exact:true}).waitFor();rows=(await read()).data;if(rows.find(r=>r.id===firstId).submission_state!=='SUBMITTED'||rows.find(r=>r.id===secondId).submission_state!=='DRAFT')throw Error('single send touched other draft');console.log('PASS saved two drafts; sending one preserves the other draft');
await p.waitForTimeout(500);await p.reload();await p.getByRole('button',{name:'Update instruction',exact:true}).waitFor();await p.getByRole('button',{name:'Update instruction',exact:true}).click();await p.getByLabel(/Request an extension/).check();await p.getByLabel('Reason — required').fill('Please request additional time to confirm the revised record.');await p.getByRole('button',{name:'Review instruction to send',exact:true}).click();await p.getByRole('button',{name:'Send instruction',exact:true}).click();await p.getByText('Instruction sent to Photon Legal.',{exact:true}).waitFor();rows=(await read()).data;if(rows[0].submission_state!=='UPDATED'||rows[0].status!=='NEW'||rows[0].version!==2)throw Error('revision not returned to Photon');console.log('PASS reload retained saved state; client revision has UPDATED/new/version2');
await p.waitForTimeout(500);await p.goto('http://127.0.0.1:3740/actions?scenario=v0/actions/action-required&role=CASE_OWNER');await p.getByRole('button',{name:'Acknowledge instruction',exact:true}).waitFor();if(!await p.getByText('Request an extension',{exact:true}).isVisible())throw Error('operator did not see retained client revision');await p.getByRole('button',{name:'Acknowledge instruction',exact:true}).click();await p.getByRole('button',{name:'Start work',exact:true}).waitFor();await p.getByRole('button',{name:'Start work',exact:true}).click();await p.getByRole('button',{name:'Mark request completed',exact:true}).waitFor();await p.getByRole('button',{name:'Mark request completed',exact:true}).click();await p.getByRole('heading',{name:'Completed',exact:true}).waitFor();const queue=await p.evaluate(async()=>await(await fetch('/v1/actions/queue')).json());if(queue.find(r=>r.id===firstId).status!=='COMPLETED')throw Error('completion did not persist');if(queue.some(r=>r.id===secondId))throw Error('unsent draft in Photon queue');console.log('PASS Case Owner acknowledges, starts and completes submitted request; unsent draft stays private');console.log('mutations',JSON.stringify(mutations));}finally{await b.close();}
