import React, { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "@/lib/toast";
import { rawApi } from "@/lib/apiConfig";
import useUserCookie from "@/hooks/use-auth";
import { usePatentEventCompletion } from "@/hooks/usePatentEventCompletion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { actionDate, actionField, actionPrimary, type ActionsWorkspaceProps, type EventRow } from "@/components/actions/ActionsWorkspace";
import PortfolioImport from "@/components/patents/PortfolioImport";

type DueEvent = EventRow & { owner?: {name:string} | null; data_issue?: string | null; source?: string; source_row?: number | null; correction_note?: string | null; updated_by?: string | null; updated_at?: string; patent: EventRow["patent"] & {client?: {id:string;name:string}; assignee_original?: string} };
type Edit = { title: string; date: string; note: string; resolve: boolean; editing: boolean };
type Props = Omit<ActionsWorkspaceProps,"rows"> & { rows: DueEvent[]; clients: {id:string;name:string}[]; clientId:string; onClient:(id:string)=>void; clientSearch:string; onClientSearch:(value:string)=>void; clientsError:boolean; retryClients:()=>void; month:string; onMonth:(value:string)=>void; initialPlanning:boolean; focusedApplication:string|null };
function urgency(row:DueEvent) { if(row.status === "COMPLETED") return "Completed"; if(!row.due_at) return "Date not recorded"; const days = Math.round((Date.parse(row.due_at.slice(0,10)) - Date.parse(new Date().toISOString().slice(0,10))) / 86400000); return days < 0 ? `${Math.abs(days)} days overdue` : days === 0 ? "Due today" : `${days} days remaining`; }
const clientName = (row:DueEvent) => row.patent?.client?.name || row.patent?.assignee_original || "Client not recorded";
export default function PhotonDueDatesWorkspace({rows,loading,error,retry,search,onSearch,filter,onFilter,pagination,onPage,clients,clientId,onClient,clientSearch,onClientSearch,clientsError,retryClients,month,onMonth,initialPlanning,focusedApplication}:Props) {
  const {user}=useUserCookie();
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [showQueue,setShowQueue]=useState(false),[showFind,setShowFind]=useState(false),[showFilters,setShowFilters]=useState(initialPlanning),[importing,setImporting]=useState(false);
  const clientNames=useRef(new Map<string,string>());
  clients.forEach(client=>clientNames.current.set(client.id,client.name));
  const selectableClients=clientId && !clients.some(c=>c.id===clientId) && clientNames.current.has(clientId) ? [{id:clientId,name:clientNames.current.get(clientId)!},...clients] : clients;
  const edits=useRef<Record<string,Edit>>({});
  const brief=useRef<HTMLDivElement>(null);
  const cache=useQueryClient();
  const selected=rows.find(r=>r.id===selectedId) || rows.find(r=>r.patent?.application_number===focusedApplication) || rows[0];
  const filtered=!!search || filter!=="open" || !!clientId || !!month;
  const clear=()=>{onSearch("");onFilter("open");onClient("");onMonth("");};
  const choose=(id:string)=>{setSelectedId(id);setShowQueue(false);requestAnimationFrame(()=>{brief.current?.focus({preventScroll:true});brief.current?.scrollIntoView({block:"nearest"});});};
  return <section data-photon-due-dates aria-label="Due dates workspace" tabIndex={0} className="min-h-0 flex-1 overflow-y-auto bg-pl-bg text-pl-ink"><div className="mx-auto w-full max-w-6xl px-6 py-3 md:py-5 lg:px-8">
    <div className="hidden flex-wrap items-start justify-between gap-3 border-b border-pl-border pb-3 md:flex"><div><h1 className="text-2xl font-semibold tracking-tight">Patent events</h1><p className="mt-1 text-sm text-pl-text-2">{user?.role==="CASE_OWNER" ? "Your assigned clients" : "All clients"} · maintain recorded deadlines</p></div><Button size="sm" variant="outline" onClick={()=>setImporting(true)}>Import spreadsheet</Button></div>
    <div className="flex flex-wrap gap-3 border-b border-pl-border py-3 md:hidden"><Button size="sm" variant="outline" aria-expanded={showFind} onClick={()=>setShowFind(!showFind)}>Find or filter events</Button><Button size="sm" variant="outline" aria-expanded={showQueue} onClick={()=>setShowQueue(!showQueue)}>{showQueue ? "Hide event list" : "Choose event"}</Button></div><div className={`${showFind ? "flex" : "hidden"} flex-wrap items-end gap-3 border-b border-pl-border py-3 md:flex`}><div className="min-w-0 flex-1"><Label htmlFor="due-search" className="text-xs text-pl-text-2">Event, patent, application or client</Label><Input id="due-search" className={`mt-2 h-9 ${actionField}`} value={search} onChange={e=>onSearch(e.target.value)}/></div><div><Label htmlFor="due-filter" className="text-xs text-pl-text-2">Show</Label><select id="due-filter" value={filter} onChange={e=>onFilter(e.target.value)} className={`mt-2 block h-9 rounded-sm border px-3 text-sm ${actionField}`}><option value="open">Open events</option><option value="overdue">Overdue</option><option value="dueSoon">Due within 7 days</option><option value="upcoming">Upcoming</option><option value="missing">Missing date</option><option value="issues">Import issues</option><option value="completed">Completed</option><option value="all">All events</option></select></div><Button size="sm" variant="outline" aria-expanded={showFilters} onClick={()=>setShowFilters(!showFilters)}>Client and month</Button><Button size="sm" variant="outline" className="hidden md:inline-flex lg:hidden" onClick={()=>setShowQueue(!showQueue)} aria-expanded={showQueue}>{showQueue ? "Hide event list" : "Choose event"}</Button><Button size="sm" variant="outline" className="md:hidden" onClick={()=>setImporting(true)}>Import spreadsheet</Button></div>
    {showFilters && <div className="flex flex-wrap items-end gap-3 border-b border-pl-border py-3"><div className="min-w-0 flex-1"><Label htmlFor="due-client-search" className="text-xs text-pl-text-2">Find a client</Label><Input id="due-client-search" className={`mt-2 h-9 ${actionField}`} value={clientSearch} onChange={e=>onClientSearch(e.target.value)}/></div><div className="min-w-0 flex-1"><Label htmlFor="due-client" className="text-xs text-pl-text-2">Client</Label><select id="due-client" value={clientId} onChange={e=>onClient(e.target.value)} className={`mt-2 block h-9 w-full rounded-sm border px-3 text-sm ${actionField}`}><option value="">All accessible clients</option>{selectableClients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><Label htmlFor="due-month" className="text-xs text-pl-text-2">Recorded month</Label><Input id="due-month" type="month" className={`mt-2 h-9 ${actionField}`} value={month} onChange={e=>onMonth(e.target.value)}/></div>{clientsError && <p role="alert" className="w-full text-sm">Clients could not be loaded. <button className="underline" onClick={retryClients}>Retry client lookup</button></p>}{month && <p className="w-full text-xs text-pl-text-2">Only events with a date in this month are shown. Clear the month to include missing dates.</p>}</div>}
    {filtered && <div className="flex flex-wrap items-center gap-3 pt-3"><p className="text-xs text-pl-text-2">Filtered events{clientId ? ` · ${clientNames.current.get(clientId) || "Selected client"}` : ""}{month ? ` · ${month}` : ""}</p><Button size="sm" variant="ghost" onClick={clear}>Clear filters</Button></div>}
    {loading ? <p role="status" className="py-10 text-sm text-pl-text-2">Loading patent events…</p> : error ? <div className="py-10"><h2 className="text-lg font-semibold">Due dates could not be loaded</h2><p className="mt-3 text-sm text-pl-text-2">Retry to retrieve the latest recorded events.</p><Button size="sm" className={`mt-5 ${actionPrimary}`} onClick={retry}>Reload due dates</Button></div> : !rows.length ? <div className="py-10"><h2 className="text-lg font-semibold">{filtered ? "No matching events" : "No open patent events"}</h2><p className="mt-3 text-sm text-pl-text-2">{filtered ? "Try another client or date range, or clear the filters." : "Completed events remain available in the Show filter. Spreadsheet imports add recorded events to this queue."}</p>{filtered && <Button size="sm" variant="outline" className="mt-5" onClick={clear}>Show open events</Button>}</div> : <div className="grid gap-4 py-3 md:py-4 lg:grid-cols-3"><nav aria-label="Recorded patent events" className={`${showQueue ? "block" : "hidden"} min-w-0 lg:block`}><p className="mb-3 text-xs text-pl-text-2">{pagination?.total ?? rows.length} events · missing dates, then earliest</p><ul className="border-t border-pl-border">{rows.map(row=><li key={row.id} className="border-b border-pl-border"><button type="button" aria-current={row.id===selected?.id ? "true" : undefined} onClick={()=>choose(row.id)} className={`w-full rounded-sm px-3 py-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--pulse-focus)] ${row.id===selected?.id ? "border-l-2 border-pl-brand bg-pl-surface" : "hover:bg-pl-surface"}`}>{row.id===selected?.id ? <span className="text-sm font-medium">Selected event →</span> : <><span className="block text-xs font-medium text-pl-text-2">{urgency(row)}{row.data_issue ? " · Check source" : ""}</span><span className="mt-2 block text-sm font-medium">{row.title}</span><span className="mt-2 block break-words text-xs text-pl-text-2">{clientName(row)} · {row.patent?.application_number || "Application not recorded"}</span></>}</button></li>)}</ul>{pagination && pagination.totalPages>1 && <div className="mt-4 flex flex-wrap items-center gap-3"><Button size="sm" variant="outline" disabled={pagination.page<=1} onClick={()=>onPage(pagination.page-1)}>Previous</Button><span className="text-xs text-pl-text-2">{pagination.page} of {pagination.totalPages}</span><Button size="sm" variant="outline" disabled={pagination.page>=pagination.totalPages} onClick={()=>onPage(pagination.page+1)}>Next</Button></div>}</nav>{selected && <div tabIndex={-1} ref={brief} className="min-w-0 focus-visible:outline-none lg:col-span-2"><EventRecord key={selected.id} row={selected} edits={edits}/></div>}</div>}
    <PortfolioImport open={importing} onOpenChange={setImporting} clients={selectableClients} selectedClientId={clientId} dueDates onImported={()=>{cache.invalidateQueries({queryKey:["all_due_dates"]});cache.invalidateQueries({queryKey:["patents"]});}}/>
  </div></section>;
}
function EventRecord({row,edits}:{row:DueEvent;edits:React.MutableRefObject<Record<string,Edit>>}) {
  const initial=()=>({title:row.title,date:row.due_at?.slice(0,10)||"",note:"",resolve:false,editing:false});
  const [edit,setEdit]=useState<Edit>(edits.current[row.id] || initial());
  const [confirm,setConfirm]=useState(false),[notice,setNotice]=useState("");
  const form=useRef<HTMLFormElement>(null);
  React.useLayoutEffect(()=>{if(edit.editing) form.current?.querySelector("input")?.focus();},[edit.editing]);
  const cache=useQueryClient(), completion=usePatentEventCompletion();
  const change=(patch:Partial<Edit>)=>{setEdit(current=>{const next={...current,...patch};edits.current[row.id]=next;return next;});};
  const save=useMutation({mutationFn:async()=>rawApi.patch(`/v1/due-dates/${row.id}`,{title:edit.title,due_at:edit.date || null,correction_note:edit.note,resolve_issue:edit.resolve}),onSuccess:()=>{delete edits.current[row.id];setEdit({...edit,editing:false,note:"",resolve:false});setNotice("Event saved.");toast.success("Event saved");cache.invalidateQueries({queryKey:["all_due_dates"]});cache.invalidateQueries({queryKey:["oc_action_queue"]});}});
  const finish=()=>completion.mutate({eventId:row.id,completed:row.status!=="COMPLETED"},{onSuccess:()=>{setConfirm(false);toast.success(row.status==="COMPLETED" ? "Event reopened" : "Event marked completed");setNotice(row.status==="COMPLETED" ? "Event reopened." : "Event marked completed.");}});
  const request=row.action?.submission_state!=="DRAFT" ? row.action : null;
  return <article aria-label="Selected patent event" className="min-w-0 bg-pl-bg"><header className={`${edit.editing || confirm ? "sticky top-0 z-10 bg-pl-bg" : ""} border-b border-pl-border pb-3`}><p className="text-xs font-medium text-pl-text-2">{edit.editing || confirm ? clientName(row) : row.status === "COMPLETED" ? "Recorded event" : !row.due_at ? "Date needs confirmation" : urgency(row)}{!edit.editing && !confirm && row.due_at && <span className="md:hidden"> · {actionDate(row.due_at)}</span>}</p><h2 className="mt-2 break-words text-base font-semibold leading-tight md:text-xl">{edit.editing ? "Edit event" : row.title}</h2>{!edit.editing && !confirm && <p className="mt-3 hidden break-words text-sm text-pl-text-2 md:block">{row.patent?.title || "Patent not recorded"}</p>}<p className="mt-2 break-words text-xs text-pl-text-2">{row.patent?.application_number || "Application number not recorded"}{!edit.editing && !confirm && <span className="md:hidden"> · {clientName(row)}</span>}</p></header>
    {row.data_issue && !edit.editing && !confirm && <div className="mt-4 border-l-2 border-pl-brand bg-pl-surface px-3 py-3"><h3 className="text-sm font-semibold">Check the recorded date</h3><p className="mt-1 text-sm text-pl-text-2">{row.data_issue}</p></div>}
    {!edit.editing && !confirm && <dl className="my-4 hidden grid-cols-2 gap-x-4 gap-y-3 border-b border-pl-border py-4 text-sm md:grid">{[["Client",clientName(row)],["Case Owner",row.owner?.name || "Unassigned"],["Recorded date",actionDate(row.due_at)],["Event status",row.status==="COMPLETED" ? "Completed" : "Pending"]].map(([label,value])=><div key={label} className="min-w-0"><dt className="text-xs text-pl-text-2">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>)}</dl>}
    {notice && <p role="status" className="mb-3 text-sm font-medium">{notice}</p>}
    {edit.editing ? <form ref={form} onSubmit={e=>{e.preventDefault();save.mutate();}} className="mt-4 space-y-4"><div><Label htmlFor="event-title">Event</Label><Input id="event-title" required value={edit.title} onChange={e=>change({title:e.target.value})} className={`mt-2 ${actionField}`}/></div><div><Label htmlFor="event-date">Recorded date</Label><Input id="event-date" type="date" value={edit.date} onChange={e=>change({date:e.target.value})} className={`mt-2 ${actionField}`} aria-describedby="event-date-help"/><p id="event-date-help" className="mt-2 text-xs text-pl-text-2">Leave blank when the date is not yet confirmed.</p></div><div><Label htmlFor="event-note">Correction note</Label><Textarea id="event-note" required value={edit.note} onChange={e=>change({note:e.target.value})} className={`mt-2 min-h-16 ${actionField}`} placeholder="What changed, and which source confirms it?"/></div>{row.data_issue && <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={edit.resolve} onChange={e=>change({resolve:e.target.checked})} className="mt-1"/>I checked the source and confirmed this date</label>}{save.isError && <p role="alert" className="text-sm">Event could not be saved. Your edits are retained; check the date and try again.</p>}<div className="sticky bottom-0 flex flex-wrap gap-3 border-t border-pl-border bg-pl-bg py-3"><Button size="sm" type="submit" className={actionPrimary} disabled={save.isPending || !edit.title.trim() || !edit.note.trim() || (edit.resolve && !edit.date)}>{save.isPending ? "Saving event…" : "Save event"}</Button><Button size="sm" type="button" variant="outline" disabled={save.isPending} onClick={()=>{setEdit(initial());delete edits.current[row.id];save.reset();}}>Cancel changes</Button></div></form> : confirm ? <div className="mt-4"><h3 className="text-base font-semibold">{row.status==="COMPLETED" ? "Reopen this event?" : "Mark this event completed?"}</h3><p className="mt-2 text-sm text-pl-text-2">{row.status==="COMPLETED" ? "The event will return to open events." : "The event will move to completed events."} The related Action keeps its current status.</p>{completion.isError && <p role="alert" className="mt-3 text-sm">The event could not be updated. Try again.</p>}<div className="mt-4 flex flex-wrap gap-3"><Button size="sm" className={actionPrimary} onClick={finish} disabled={completion.isPending}>{completion.isPending ? "Updating event…" : row.status==="COMPLETED" ? "Reopen event" : "Confirm completion"}</Button><Button size="sm" variant="outline" onClick={()=>setConfirm(false)} disabled={completion.isPending}>Keep current status</Button></div></div> : <div className="mt-3 flex flex-wrap gap-3 bg-pl-bg py-2 md:mt-0"><Button size="sm" className={actionPrimary} onClick={()=>{change({editing:true});setNotice("");}}>Edit event</Button><Button size="sm" variant="outline" onClick={()=>{setConfirm(true);setNotice("");}}>{row.status==="COMPLETED" ? "Reopen event…" : "Mark completed…"}</Button></div>}
    {!edit.editing && !confirm && <details className="mt-3 border-t border-pl-border pt-3 md:hidden"><summary className="cursor-pointer text-sm text-pl-text-2">Owner, status and patent title</summary><p className="mt-3 text-sm">Case Owner: {row.owner?.name || "Unassigned"}</p><p className="mt-2 text-sm">Event status: {row.status === "COMPLETED" ? "Completed" : "Pending"}</p><p className="mt-2 break-words text-sm">{row.patent?.title || "Patent not recorded"}</p></details>}
    <div className="mt-5 border-t border-pl-border pt-4"><h3 className="text-xs font-medium text-pl-text-2">Related Action</h3>{request ? <Link to={`/actions?search=${encodeURIComponent(row.patent?.application_number || row.title)}`} className="mt-2 inline-block text-sm underline underline-offset-4">View client instruction →</Link> : <p className="mt-2 text-sm text-pl-text-2">No client instruction submitted.</p>}{row.patent?.id && <Link to={`/patents/${row.patent.id}`} className="mt-3 block text-sm underline underline-offset-4">Open patent details →</Link>}</div><details className="mt-4 border-t border-pl-border pt-3"><summary className="cursor-pointer text-sm text-pl-text-2">Source and latest correction</summary><p className="mt-3 text-sm">{row.source || "Manual Photon update"}{row.source_row ? ` · row ${row.source_row}` : ""}</p>{row.correction_note && <p className="mt-2 break-words text-sm text-pl-text-2">{row.correction_note}</p>}<p className="mt-2 text-xs text-pl-text-2">Last updated {actionDate(row.updated_at)}{row.updated_by ? ` by ${row.updated_by}` : ""}</p></details>
  </article>;
}
