import React, { useState, useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowUpRight, ChevronDown, Download, Loader2, Pencil, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/DashboardChrome";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import API_CONFIG, { rawApi } from "@/lib/apiConfig";
import { s3Upload } from "@/lib/api-service/s3Upload";
import useUserCookie from "@/hooks/use-auth";
import { MAX_FILE_SIZE } from "@/utils/constants";

type PatentStatus = "APPLIED" | "EXAMINATION" | "GRANTED" | "EXPIRED" | "WITHDRAWN" | "REJECTED" | "ABANDONED" | "NONPAYMENT";
const statuses: Record<PatentStatus, string> = { APPLIED: "Applied", EXAMINATION: "In examination", GRANTED: "Granted", EXPIRED: "Expired", WITHDRAWN: "Withdrawn", REJECTED: "Rejected", ABANDONED: "Abandoned", NONPAYMENT: "Lapsed for nonpayment" };
const countries: Record<string, string> = { US: "United States", EP: "European Patent Office", IN: "India", WO: "International (PCT)", GB: "United Kingdom", CN: "China", JP: "Japan", DE: "Germany", KR: "South Korea", CA: "Canada", AU: "Australia", FR: "France" };
type Document = { id: string; original_name: string; size_bytes: number; content_type: string };
type Patent = { client?: { name: string } | null; id: string; client_id: string; title: string; application_number: string | null; jurisdiction: string; status: PatentStatus; filing_date: string | null; grant_date: string | null; inventors: string[]; current_assignee: string | null; assignee_original: string | null; abstract: string | null; simple_family_members: string[]; additional_notes: string | null; prn: string | null; oc: string | null; next_steps_gpo: string[]; next_steps_legal: string[]; status_timeline_history: { status: string; date: string }[]; files: Document[]; due_dates: { id: string; title: string; due_at: string; status: string }[]; idea_link: { idea: { id: string; title: string; reference?: string } } | null };
type Draft = Pick<Patent, "title" | "jurisdiction" | "status" | "application_number" | "filing_date" | "grant_date" | "current_assignee" | "assignee_original" | "abstract" | "additional_notes" | "prn" | "oc" | "status_timeline_history"> & { inventors: string; simple_family_members: string; next_steps_gpo: string; next_steps_legal: string };
const date = (value?: string | null) => value && !Number.isNaN(Date.parse(value)) ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(value)) : "Not recorded";
const lines = (value: string) => value.split("\n").map(v => v.trim()).filter(Boolean);
const fieldClass = "bg-pl-bg border-pl-border text-pl-ink focus-visible:ring-[var(--pulse-focus)]";
const primary = "bg-pl-brand text-pl-ink hover:bg-pl-brand-deep";
function Fact({ label, children }: { label: string; children: React.ReactNode }) { return <div className="min-w-0"><dt className="text-xs text-pl-text-2">{label}</dt><dd className="mt-1 break-words text-sm text-pl-ink">{children || "Not recorded"}</dd></div>; }
function Evidence({ title, count, children, open = false }: { title: string; count?: number; children: React.ReactNode; open?: boolean }) { return <details open={open || undefined} className="group border-b border-pl-border py-4"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-sm text-sm font-semibold text-pl-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--pulse-focus)]"><ChevronDown aria-hidden="true" className="h-4 w-4 shrink-0 transition-transform group-open:rotate-180 motion-reduce:transition-none"/>{title}{count !== undefined && <span className="font-normal text-pl-text-2">({count})</span>}</summary><div className="pt-4 text-sm text-pl-text-2">{children}</div></details>; }
const draftFor = (p: Patent): Draft => ({ title: p.title, application_number: p.application_number, jurisdiction: p.jurisdiction, status: p.status, filing_date: p.filing_date?.slice(0,10) || "", grant_date: p.grant_date?.slice(0,10) || "", current_assignee: p.current_assignee, assignee_original: p.assignee_original, abstract: p.abstract, additional_notes: p.additional_notes, prn: p.prn, oc: p.oc, inventors: (p.inventors || []).join("\n"), simple_family_members: (p.simple_family_members || []).join("\n"), next_steps_gpo: (p.next_steps_gpo || []).join("\n"), next_steps_legal: (p.next_steps_legal || []).join("\n"), status_timeline_history: (p.status_timeline_history || []).map(t => ({ ...t, date: t.date.slice(0,10) })) });

export default function PatentDetailsContent({ patentId }: { patentId: string }) {
  const { user } = useUserCookie(); const cache = useQueryClient();
  const canEdit = user?.role === "CASE_OWNER" || user?.role === "PHOTON_ADMIN";
  const showDates = !!user && user.role !== "INVENTOR";
  const [draft, setDraft] = useState<Draft | null>(null); const [validation, setValidation] = useState(""); const [saved, setSaved] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  const [removeCandidate, setRemoveCandidate] = useState<Document | null>(null);
  const [file, setFile] = useState<File | null>(null); const [documentError, setDocumentError] = useState(""); const [downloadId, setDownloadId] = useState<string | null>(null);
  // Preserve the detail query identity and endpoint. Read canonical fields: the
  // legacy adapter synthesizes missing filing dates and replaces patent inventors.
  const query = useQuery({ queryKey: ["patentDetails", patentId], queryFn: async () => { const response = await rawApi.get<Patent>(`/v1/patents/${patentId}`); return { data: response.data }; }, retry: false });
  const patent = query.data?.data;
  useEffect(() => { setDraft(null); setFile(null); setSaved(false); setRemoveCandidate(null); setValidation(""); setDocumentError(""); }, [patentId]);
  const refresh = async () => { await cache.invalidateQueries({ queryKey: ["patentDetails", patentId] }); await cache.invalidateQueries({ queryKey: ["patents"] }); await cache.invalidateQueries({ queryKey: ["portfolio-stats"] }); };
  const save = useMutation({ mutationFn: async (edit: Draft) => API_CONFIG.put(`/api/v1/patent/update-single/${patentId}`, { ...edit, title: edit.title.trim(), filing_date: edit.filing_date || null, grant_date: edit.grant_date || null, inventors: lines(edit.inventors), simple_family_members: lines(edit.simple_family_members), next_steps_gpo: lines(edit.next_steps_gpo), next_steps_legal: lines(edit.next_steps_legal) }), onSuccess: async () => { await refresh(); setDraft(null); setSaved(true); }, onError: () => {} });
  const upload = useMutation({ mutationFn: async () => { if (!file || !patent) throw new Error("Choose a document first."); const stored = await s3Upload(file, "patent", patent.client_id); await API_CONFIG.put(`/api/v1/patent/update-single/${patentId}`, { documents: [stored.id] }); }, onSuccess: async () => { await refresh(); setFile(null); if (fileInput.current) fileInput.current.value = ""; setDocumentError(""); }, onError: () => setDocumentError("Document could not be added. Your selected file is retained; try again.") });
  const remove = useMutation({ mutationFn: async (id: string) => rawApi.delete(`/v1/files/${id}`), onSuccess: async () => { await refresh(); setRemoveCandidate(null); }, onError: () => setDocumentError("Document could not be removed. Try again.") });
  const download = async (doc: Document) => { setDownloadId(doc.id); setDocumentError(""); try { const response = await rawApi.get(`/v1/files/${doc.id}/raw`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const a = document.createElement("a"); a.href = url; a.download = doc.original_name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch { setDocumentError(`Could not download ${doc.original_name}. Try again.`); } finally { setDownloadId(null); } };
  const set = (key: keyof Draft, value: string) => { setDraft(old => old && ({ ...old, [key]: value })); setValidation(""); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!draft) return; if (!draft.title.trim()) { setValidation("Enter a patent title."); return; } if (draft.filing_date && draft.grant_date && draft.grant_date < draft.filing_date) { setValidation("Grant date must be on or after the filing date."); return; } if (draft.status_timeline_history.some(t => !t.status.trim() || !t.date)) { setValidation("Each lifecycle event needs a status and date. Complete or remove the empty event."); return; } save.mutate(draft); };

  const navigation = user?.role === "INVENTOR" ? [["Home","/"],["Ideas","/ideas"],["Patents","/patents"],["Profile","/profile"]] : user?.role === "LEGAL_COUNSEL" ? [["Home","/"],["Ideas","/ideas"],["Patents","/patents"],["Actions","/due-dates"],["Workspace","/workspace"],["Profile","/profile"]] : [[user?.role === "CASE_OWNER" ? "My work" : "Dashboard","/"],["Clients","/clients"],["Ideas","/ideas"],["Patents","/patents"],["Due dates","/due-dates"],["Actions","/actions"],...(user?.role === "PHOTON_ADMIN" ? [["Workspace","/workspace"]] : []),["Profile","/profile"]];
  const textField = (key: keyof Draft, label: string, type = "text", multiline = false) => <div className="min-w-0"><Label htmlFor={`patent-${key}`} className="text-sm text-pl-ink">{label}</Label>{multiline ? <Textarea id={`patent-${key}`} className={`mt-2 ${fieldClass}`} value={String(draft?.[key] ?? "")} onChange={e => set(key,e.target.value)}/> : <Input id={`patent-${key}`} type={type} required={key === "title"} className={`mt-2 h-9 ${fieldClass}`} value={String(draft?.[key] ?? "")} onChange={e => set(key,e.target.value)}/>}</div>;
  return <section data-patent-detail tabIndex={0} aria-label="Patent record" className="min-h-0 flex-1 overflow-y-auto bg-pl-bg text-pl-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[var(--pulse-focus)]">
    <PageHeader title={canEdit && patent?.client?.name ? `${patent.client.name} · Patent detail` : undefined} actions={<DropdownMenu><DropdownMenuTrigger asChild><Button size="sm" variant="outline" className="md:hidden">Navigation <ChevronDown aria-hidden="true"/></Button></DropdownMenuTrigger><DropdownMenuContent className="bg-pl-bg text-pl-ink motion-reduce:!animate-none" align="end">{navigation.map(([label,path]) => <DropdownMenuItem key={path} asChild><Link to={path}>{label}</Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>}/>
    <div className="mx-auto w-full max-w-6xl px-6 py-6 lg:px-8">

      {query.isLoading ? <p role="status" className="py-12 text-sm text-pl-text-2">Loading patent record…</p> : query.isError || !patent ? <div className="py-12"><h1 className="text-2xl font-semibold">Patent could not be loaded</h1><p className="mt-3 text-sm text-pl-text-2">The record may be unavailable or outside your workspace. Try again or return to the portfolio.</p><Button size="sm" className={`mt-6 ${primary}`} onClick={() => query.refetch()}>Reload patent</Button></div> : <>
      <header className="border-b border-pl-border pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><p className="mb-2 text-xs font-medium text-pl-text-2">PATENT RECORD</p><h1 className="break-words text-2xl font-semibold leading-tight tracking-tight">{patent.title}</h1><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm"><span className="break-all text-pl-text-2">{patent.application_number || "Application number not recorded"}</span><span className="font-medium">{statuses[patent.status] || "Status not recorded"}</span><span className="text-pl-text-2">{countries[patent.jurisdiction] || patent.jurisdiction || "Jurisdiction not recorded"}</span></div></div>{canEdit && !draft && <Button size="sm" className={primary} onClick={() => { setDraft(draftFor(patent)); setSaved(false); save.reset(); }}><Pencil aria-hidden="true" className="mr-2 h-4 w-4"/>Edit patent</Button>}</div></header>
      {saved && <p role="status" className="mt-4 text-sm text-pl-ink">Patent changes saved.</p>}
      {draft ? <form onSubmit={submit} className="pt-6"><div className="sticky top-0 z-10 border-b border-pl-border bg-pl-bg pb-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Edit patent record</h2>{(validation || save.isError) && <p role="alert" className="mt-4 text-sm text-pl-ink">{validation || "Patent changes could not be saved. Your edits are retained; try again."}</p>}<div className="flex flex-wrap items-center gap-3"><Button size="sm" type="submit" disabled={save.isPending} className={primary}>{save.isPending && <Loader2 aria-hidden="true" className="mr-2 h-4 w-4 animate-spin motion-reduce:animate-none"/>}{save.isPending ? "Saving patent…" : "Save patent changes"}</Button><Button size="sm" type="button" variant="outline" disabled={save.isPending} onClick={() => { setDraft(null); setValidation(""); save.reset(); }}>Cancel</Button></div></div><p className="mt-2 text-sm text-pl-text-2">Update recorded information. Leave unknown dates blank.</p></div><fieldset disabled={save.isPending} className="mt-6 space-y-6"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2">{textField("title", "Patent title")}</div>{textField("application_number", "Application number")}{textField("jurisdiction", "Jurisdiction code")}<div><Label htmlFor="patent-status">Legal status</Label><select id="patent-status" value={draft.status} onChange={e => set("status",e.target.value)} className={`mt-2 h-9 w-full rounded-md border px-3 text-sm ${fieldClass}`}>{Object.entries(statuses).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></div>{textField("filing_date", "Filing date", "date")}{textField("grant_date", "Grant date", "date")}{textField("current_assignee", "Current assignee")}{textField("assignee_original", "Original assignee")}{textField("inventors", "Inventors — one name per line", "text",true)}</div>{textField("abstract", "Abstract", "text",true)}
      <Evidence title="Family and lifecycle"><div className="space-y-4">{textField("simple_family_members", "Family application numbers — one per line", "text",true)}<p className="text-sm">Record only documented events.</p>{draft.status_timeline_history.map((event,index) => <div className="flex flex-wrap items-end gap-3" key={index}><div className="min-w-0 flex-1"><Label htmlFor={`event-status-${index}`}>Event {index + 1}</Label><Input className={`mt-2 ${fieldClass}`} id={`event-status-${index}`} value={event.status} onChange={e => setDraft({...draft,status_timeline_history:draft.status_timeline_history.map((t,i) => i === index ? {...t,status:e.target.value} : t)})}/></div><div><Label htmlFor={`event-date-${index}`}>Date {index + 1}</Label><Input className={`mt-2 ${fieldClass}`} type="date" id={`event-date-${index}`} value={event.date} onChange={e => setDraft({...draft,status_timeline_history:draft.status_timeline_history.map((t,i) => i === index ? {...t,date:e.target.value} : t)})}/></div><Button size="sm" type="button" variant="outline" aria-label={`Remove event ${index+1}`} onClick={() => setDraft({...draft,status_timeline_history:draft.status_timeline_history.filter((_,i) => i !== index)})}><Trash2 aria-hidden="true" className="h-4 w-4"/></Button></div>)}<Button size="sm" type="button" variant="outline" onClick={() => setDraft({...draft,status_timeline_history:[...draft.status_timeline_history,{status:"",date:""}]})}><Plus aria-hidden="true" className="mr-2 h-4 w-4"/>Add lifecycle event</Button></div></Evidence>
      <Evidence title="Maintenance notes"><div className="grid gap-4 sm:grid-cols-2">{textField("prn", "Reference number")}{textField("oc", "External counsel")}{textField("additional_notes", "Notes", "text",true)}{textField("next_steps_legal", "Legal next steps — one per line", "text",true)}{textField("next_steps_gpo", "Operations next steps — one per line", "text",true)}</div></Evidence></fieldset></form> : <div className="grid gap-8 pt-6 lg:grid-cols-3"><aside className={`${!canEdit && (patent.idea_link?.idea || showDates) ? "lg:order-last" : "order-last"} min-w-0 space-y-6`}>{showDates && <section><h2 className="text-sm font-semibold">Upcoming dates</h2>{patent.due_dates?.filter(d => d.status === "PENDING").length ? <ul className="mt-3 space-y-4">{patent.due_dates.filter(d => d.status === "PENDING").slice(0,3).map(d => <li key={d.id}><p className="text-sm">{d.title}</p><p className="mt-1 text-sm text-pl-text-2">{date(d.due_at)}</p></li>)}</ul> : <p className="mt-3 text-sm text-pl-text-2">No upcoming dates recorded.</p>}<Button asChild size="sm" variant="outline" className={`mt-3 ${user?.role === "LEGAL_COUNSEL" ? primary : ""}`}><Link to={`/due-dates?search=${encodeURIComponent(patent.application_number || patent.title)}`}>View {canEdit ? "due dates" : "Actions"}<ArrowUpRight aria-hidden="true" className="ml-2 h-4 w-4"/></Link></Button></section>}<section className={showDates ? "border-t border-pl-border pt-4" : ""}><h2 className="text-sm font-semibold">Originating idea</h2>{patent.idea_link?.idea ? <><p className="mt-3 break-words text-sm text-pl-text-2">{patent.idea_link.idea.reference || "Invention disclosure"}{patent.idea_link.idea.title !== patent.title && <> · {patent.idea_link.idea.title}</>}</p><Button asChild size="sm" variant="outline" className={`mt-3 ${user?.role === "INVENTOR" ? primary : ""}`}><Link to={`/ideas/${patent.idea_link.idea.id}`}>View invention disclosure<ArrowUpRight aria-hidden="true" className="ml-2 h-4 w-4"/></Link></Button></> : <p className="mt-3 text-sm text-pl-text-2">No originating idea is available for this record.</p>}</section>
      
      {canEdit && (!patent.application_number || !patent.filing_date || !patent.abstract || !patent.inventors?.length) && <section className="border-t border-pl-border pt-4"><h2 className="text-sm font-semibold">Record needs detail</h2><p className="mt-3 text-sm leading-relaxed text-pl-text-2">{[!patent.application_number && "Application number",!patent.filing_date && "filing date",!patent.abstract && "abstract",!patent.inventors?.length && "inventors"].filter(Boolean).join(", ")} not recorded. Use Edit patent to add verified information.</p></section>}</aside><div className="min-w-0 lg:col-span-2"><h2 className="sr-only">Record details</h2><dl className="grid gap-x-6 gap-y-5 sm:grid-cols-2"><Fact label="Filing date">{date(patent.filing_date)}</Fact><Fact label="Grant date">{date(patent.grant_date)}</Fact><Fact label="Inventors">{(patent.inventors || []).join(", ")}</Fact><Fact label="Current assignee">{patent.current_assignee}</Fact></dl><section className="py-6"><h2 className="text-sm font-semibold">Abstract</h2><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed text-pl-text-2">{patent.abstract || "No abstract has been recorded."}</p></section>
      <Evidence title="Patent family" count={(patent.simple_family_members || []).length}>{patent.simple_family_members?.length ? <ul className="space-y-2">{patent.simple_family_members.map((member,index) => <li key={index} className="break-all">{member}</li>)}</ul> : <p>No family members recorded.</p>}</Evidence>
      <Evidence title="Documents" count={(patent.files || []).length}><div className="space-y-3">{patent.files?.length ? patent.files.map(doc => <div key={doc.id} className="flex flex-wrap items-center gap-2 border-b border-pl-border pb-3"><div className="min-w-0 flex-1"><p className="break-all text-pl-ink">{doc.original_name}</p><p className="mt-1 text-xs">{Math.max(1,Math.round(doc.size_bytes / 1024))} KB</p></div><Button variant="ghost" size="sm" disabled={downloadId === doc.id} onClick={() => download(doc)} aria-label={`Download ${doc.original_name}`}><Download aria-hidden="true" className="h-4 w-4"/></Button>{canEdit && <Button variant="ghost" size="sm" disabled={remove.isPending} onClick={() => { setRemoveCandidate(doc); setDocumentError(""); }} aria-label={`Remove ${doc.original_name}`}><Trash2 aria-hidden="true" className="h-4 w-4"/></Button>}</div>) : <p>No documents recorded.</p>}{canEdit && <div className="pt-2"><Label htmlFor="patent-document" className="text-pl-ink">Add a document</Label><Input ref={fileInput} id="patent-document" type="file" className={`mt-2 ${fieldClass}`} disabled={upload.isPending} onChange={e => { const selected = e.target.files?.[0] || null; if (selected && selected.size > MAX_FILE_SIZE) { setDocumentError(`Choose a document smaller than ${Math.round(MAX_FILE_SIZE / 1024 / 1024)} MB.`); setFile(null); } else { setFile(selected); setDocumentError(""); } }}/>{file && <p className="mt-2 break-all text-xs">Selected: {file.name}</p>}<Button variant="outline" size="sm" className="mt-3" disabled={!file || upload.isPending} onClick={() => upload.mutate()}>{upload.isPending ? "Adding document…" : "Add document"}</Button></div>}{removeCandidate && <div className="border-t border-pl-border pt-3"><p className="break-words text-pl-ink">Remove {removeCandidate.original_name} from this patent?</p><div className="mt-3 flex gap-2"><Button variant="outline" size="sm" disabled={remove.isPending} onClick={() => remove.mutate(removeCandidate.id)}>{remove.isPending ? "Removing…" : "Remove document"}</Button><Button variant="ghost" size="sm" disabled={remove.isPending} onClick={() => setRemoveCandidate(null)}>Keep document</Button></div></div>}{documentError && <p role="alert" className="text-pl-ink">{documentError}</p>}</div></Evidence>
      <Evidence title="Lifecycle history" count={(patent.status_timeline_history || []).length}>{patent.status_timeline_history?.length ? <ol className="space-y-3">{[...patent.status_timeline_history].sort((a,b) => b.date.localeCompare(a.date)).map((event,index) => <li key={index} className="flex flex-wrap gap-x-4 gap-y-1"><span className="text-pl-ink">{statuses[event.status as PatentStatus] || event.status}</span><span>{date(event.date)}</span></li>)}</ol> : <p>No lifecycle events recorded.</p>}</Evidence>
      <Evidence title="Additional record details"><dl className="grid gap-5 sm:grid-cols-2"><Fact label="Original assignee">{patent.assignee_original}</Fact>{canEdit && <><Fact label="Reference number">{patent.prn}</Fact><Fact label="External counsel">{patent.oc}</Fact></>}</dl></Evidence>
      {canEdit && <Evidence title="Maintenance notes"><div className="space-y-4"><p className="whitespace-pre-wrap break-words">{patent.additional_notes || "No maintenance notes recorded."}</p>{!!patent.next_steps_legal?.length && <div><h3 className="font-medium text-pl-ink">Legal next steps</h3><ul className="mt-2 space-y-2">{patent.next_steps_legal.map((step,index) => <li key={index}>{step}</li>)}</ul></div>}{!!patent.next_steps_gpo?.length && <div><h3 className="font-medium text-pl-ink">Operations next steps</h3><ul className="mt-2 space-y-2">{patent.next_steps_gpo.map((step,index) => <li key={index}>{step}</li>)}</ul></div>}</div></Evidence>}</div>
      </div>}
      </>}
    </div>
  </section>;
}
