import React, { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronDown, ArrowUpRight } from "lucide-react";
import { rawApi } from "@/lib/apiConfig";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader } from "@/components/DashboardChrome";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import useUserCookie from "@/hooks/use-auth";
import { track } from "@/lib/analytics";

export type Instruction = { id: string; template_id: string | null; instruction: string | null; submission_state: string; status: string; selected_countries: string[]; note: string | null; version: number; requested_at: string; requested_by?: { name: string } | null; response_note?: string | null };
export type EventRow = { id: string; title: string; event_type: string; due_at: string | null; status?: string; patent: { id: string; title: string; application_number: string | null }; client?: { id: string; name: string } | null; action: Instruction | null };
type Template = { id: string; label: string; description: string; requires_countries: boolean; requires_note: boolean };
type LocalInstruction = { editing: boolean; templateId: string; selectedCountries: string[]; note: string };
type Page = { page: number; total: number; totalPages: number };
export const actionPrimary = "bg-pl-brand text-pl-ink hover:bg-pl-brand-deep";
export const actionField = "border-pl-border bg-pl-bg text-pl-ink focus-visible:ring-[var(--pulse-focus)]";
const statusLabels: Record<string,string> = { NEW: "Submitted", ACKNOWLEDGED: "Acknowledged", IN_PROGRESS: "In progress", COMPLETED: "Completed", DECLINED: "Declined", NO_ACTION: "Instruction needed" };
const countryNames = new Intl.DisplayNames(["en"], { type: "region" });
const countries = ["US","CA","MX","GB","DE","FR","ES","IT","NL","SE","CH","AT","BE","DK","FI","IE","NO","PL","PT","CZ","GR","HU","RO","CN","JP","KR","IN","SG","TW","HK","TH","MY","ID","PH","VN","IL","AU","NZ","BR","AR","CL","CO","PE","ZA","EG","NG","KE","MA","AE","SA","QA","KW","BH"];
export const actionDate = (value: string | null | undefined) => value && !Number.isNaN(Date.parse(value)) ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(value)) : "Date not recorded";
export function deadline(row: EventRow) { if (row.action?.status === "COMPLETED" || row.status === "COMPLETED") return "Event complete"; if (!row.due_at || Number.isNaN(Date.parse(row.due_at))) return "Date not recorded"; const days = Math.round((Date.parse(row.due_at.slice(0,10)) - Date.parse(new Date().toISOString().slice(0,10))) / 86400000); return days < 0 ? `${Math.abs(days)} days overdue` : days === 0 ? "Due today" : `${days} days remaining`; }
const state = (row: EventRow) => row.action?.submission_state === "DRAFT" ? "Draft saved" : row.action?.submission_state === "UPDATED" && row.action.status === "NEW" ? "Updated instruction" : row.action ? statusLabels[row.action.status] || "Status not recorded" : row.status === "COMPLETED" ? "No instruction required" : "Instruction needed";
const ownership = (row: EventRow, operator: boolean) => !row.action || row.action.submission_state === "DRAFT" ? row.status === "COMPLETED" ? "This event is complete. No instruction is required." : "The Workspace Admin owns the next step: send an instruction to Photon Legal." : row.action.status === "DECLINED" ? "The Workspace Admin owns the next step: review Photon Legal’s response." : row.action.status === "COMPLETED" ? "Photon Legal has finished this request. No further step is pending." : operator ? "Photon Legal owns the next step: process the client’s instruction." : "Photon Legal owns the next step. You can follow its progress here.";

export function ActionsNavigation() {
  const {user} = useUserCookie();
  const ops = user?.role === "CASE_OWNER" || user?.role === "PHOTON_ADMIN";
  const paths = ops ? [[user?.role === "CASE_OWNER" ? "My work" : "Dashboard", "/"],["Clients","/clients"],["Ideas","/ideas"],["Patents","/patents"],["Due dates","/due-dates"],["Actions","/actions"], ...(user?.role === "PHOTON_ADMIN" ? [["Workspace","/workspace"]] : []),["Profile","/profile"]] : [["Home","/"],["Ideas","/ideas"],["Patents","/patents"],["Actions","/due-dates"],["Workspace","/workspace"],["Profile","/profile"]];
  return <DropdownMenu><DropdownMenuTrigger asChild><Button size="sm" variant="outline" className="md:hidden">Navigation <ChevronDown aria-hidden="true"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="bg-pl-bg text-pl-ink motion-reduce:!animate-none">{paths.map(([label,path])=><DropdownMenuItem key={path} asChild><Link to={path}>{label}</Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>;
}

export type ActionsWorkspaceProps = { rows: EventRow[]; loading: boolean; error: boolean; retry: () => void; search: string; onSearch: (value: string) => void; filter: string; onFilter: (value: string) => void; pagination?: Page; onPage: (page: number) => void; operator?: boolean; extraFilters?: React.ReactNode; header?: boolean };
export default function ActionsWorkspace({ rows, loading, error, retry, search, onSearch, filter, onFilter, pagination, onPage, operator = false, extraFilters, header = true }: ActionsWorkspaceProps) {
  const draftCache = useRef<Record<string,LocalInstruction>>({});
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showQueue, setShowQueue] = useState(false);
  const selected = rows.find(row => row.id === selectedId) || rows[0];
  const brief = useRef<HTMLDivElement>(null);
  const { user } = useUserCookie();
  useEffect(() => { setShowQueue(false); }, [search, filter]);
  const pick = (id: string) => { setSelectedId(id); setShowQueue(false); requestAnimationFrame(() => { brief.current?.focus({ preventScroll: true }); brief.current?.scrollIntoView({ block: "nearest" }); }); };
  return <section data-actions-workspace className="min-h-0 flex-1 overflow-y-auto bg-pl-bg text-pl-ink" aria-label="Actions workspace" tabIndex={0}>
    {header && <PageHeader title={operator ? selected?.client?.name ? `${selected.client.name} · Actions` : user?.role === "CASE_OWNER" ? "Assigned clients · Actions" : "All clients · Actions" : "Actions"} actions={<ActionsNavigation/>}/>}
    <div className="mx-auto w-full max-w-6xl px-6 py-6 lg:px-8">
      <div className="border-b border-pl-border pb-5"><h1 className="text-2xl font-semibold tracking-tight">{operator ? "Client instructions" : "Patent event instructions"}</h1><p className="mt-2 text-sm text-pl-text-2">{operator ? "Process submitted requests, with the next owner clear at each step." : "Send Photon Legal your instruction for an upcoming patent event."}</p></div>
      <div className="flex flex-wrap items-end gap-3 border-b border-pl-border py-4"><div className="min-w-0 flex-1"><Label htmlFor="actions-search" className="text-xs text-pl-text-2">Patent, application or event</Label><Input id="actions-search" value={search} onChange={e => onSearch(e.target.value)} className={`mt-2 h-9 ${actionField}`}/></div><div><Label htmlFor="actions-window" className="text-xs text-pl-text-2">Deadline</Label><select id="actions-window" className={`mt-2 block h-9 rounded-md border px-3 text-sm ${actionField}`} value={filter} onChange={e => onFilter(e.target.value)}><option value="all">All dates</option><option value="overdue">Overdue</option><option value="dueToday">Due today</option><option value="upcoming">Upcoming</option>{!operator && <option value="completed">Completed events</option>}</select></div>{extraFilters}</div>
      {loading ? <p role="status" className="py-12 text-sm text-pl-text-2">Loading events and instructions…</p> : error ? <div className="py-10"><h2 className="text-lg font-semibold">Actions could not be loaded</h2><p className="mt-3 text-sm text-pl-text-2">Try again to retrieve the latest events and instructions.</p><Button size="sm" className={`mt-5 ${actionPrimary}`} onClick={retry}>Reload Actions</Button></div> : !rows.length ? <div className="py-10"><h2 className="text-lg font-semibold">{search || filter !== "all" ? "No matching events" : operator ? "No submitted instructions" : "No upcoming event needs an instruction"}</h2><p className="mt-3 text-sm text-pl-text-2">{search || filter !== "all" ? "Clear the search and deadline filter to see other events." : operator ? "Client instructions will appear here after they are sent to Photon Legal." : "New patent events will appear here when they need your attention."}</p>{(search || filter !== "all") && <Button size="sm" variant="outline" className="mt-5" onClick={()=>{onSearch("");onFilter("all");}}>Clear event filters</Button>}</div> : <>
      <div className="grid gap-6 py-6 lg:grid-cols-3"><nav aria-label="Patent events" className="min-w-0"><Button size="sm" variant="outline" className="mb-3 lg:hidden" onClick={()=>setShowQueue(!showQueue)}>{showQueue ? "Hide event list" : "Choose another event"}</Button><div className={`${showQueue ? "block" : "hidden"} lg:block`}><p className="mb-3 text-xs text-pl-text-2">{pagination ? `${pagination.total} ${pagination.total === 1 ? "event" : "events"} · earliest deadline first` : "Earliest deadline first"}</p><ul className="border-t border-pl-border">{rows.map(row=><li key={row.id} className="border-b border-pl-border"><button type="button" aria-current={selected?.id === row.id ? "true" : undefined} onClick={()=>pick(row.id)} className={`w-full rounded-sm px-3 py-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--pulse-focus)] ${selected?.id === row.id ? "border-l-2 border-pl-brand bg-pl-surface" : "hover:bg-pl-surface"}`}>{selected?.id === row.id ? <span className="text-sm font-medium">Selected event →</span> : <><span className="block text-sm font-medium">{row.title}</span><span className="mt-2 block break-words text-xs text-pl-text-2">{operator && row.client?.name ? `${row.client.name} · ` : ""}{row.patent?.application_number || "Application number not recorded"}</span><span className="mt-2 block text-xs text-pl-text-2">{actionDate(row.due_at)} · {deadline(row)}</span><span className="mt-1 block text-xs text-pl-text-2">{state(row)}</span></>}</button></li>)}</ul>{pagination && pagination.totalPages > 1 && <div className="mt-4 flex flex-wrap items-center gap-3"><Button size="sm" variant="outline" disabled={pagination.page <= 1} onClick={()=>onPage(pagination.page - 1)}>Previous</Button><span className="text-xs text-pl-text-2">{pagination.page} of {pagination.totalPages}</span><Button size="sm" variant="outline" disabled={pagination.page >= pagination.totalPages} onClick={()=>onPage(pagination.page + 1)}>Next</Button></div>}</div></nav>
      {selected && <div ref={brief} tabIndex={-1} className="min-w-0 focus-visible:outline-none lg:col-span-2"><InstructionBrief key={selected.id} row={selected} operator={operator} draftCache={draftCache}/></div>}</div>
      </>}
    </div>
  </section>;
}

function InstructionBrief({ row, operator, draftCache }: { row: EventRow; operator: boolean; draftCache: React.MutableRefObject<Record<string,LocalInstruction>> }) {
  const cache = useQueryClient();
  const [editing, setEditing] = useState(draftCache.current[row.id]?.editing ?? (!row.action || row.action.submission_state === "DRAFT"));
  const [templateId, setTemplateId] = useState(draftCache.current[row.id]?.templateId ?? row.action?.template_id ?? "");
  const [selectedCountries, setCountries] = useState(draftCache.current[row.id]?.selectedCountries ?? row.action?.selected_countries ?? []);
  const [note, setNote] = useState(draftCache.current[row.id]?.note ?? row.action?.note ?? "");
  useEffect(() => { draftCache.current[row.id] = { editing, templateId, selectedCountries, note }; }, [draftCache, row.id, editing, templateId, selectedCountries, note]);
  const [countrySearch, setCountrySearch] = useState("");
  const [confirmation, setConfirmation] = useState(false);
  const confirmRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (confirmation) { confirmRef.current?.focus({preventScroll:true}); confirmRef.current?.scrollIntoView({block:"nearest"}); } }, [confirmation]);
  const [declining, setDeclining] = useState(false);
  const [responseNote, setResponseNote] = useState("");
  const [notice, setNotice] = useState("");
  const request = row.action;
  const templates = useQuery({queryKey:["action_templates_event",row.event_type],queryFn:async()=>{const r=await rawApi.get<Template[]>(`/v1/actions/templates?event_type=${encodeURIComponent(row.event_type)}`);return r.data;},enabled:!operator && editing && row.status !== "COMPLETED",retry:false});
  const template = templates.data?.find(t=>t.id===templateId);
  const refresh = async()=>{for(const key of ["all_due_dates","ihc_actions","oc_action_queue","dashboard"])await cache.invalidateQueries({queryKey:[key]});};
  const save = useMutation({mutationFn:async(send:boolean)=>{if(!template)throw Error("Choose an available instruction.");const result=await rawApi.patch<Instruction>(`/v1/actions/${request?.id || row.id}`,{due_date_id:row.id,template_id:template.id,instruction:template.label,selected_countries:template.requires_countries?selectedCountries:[],note:note.trim() || null});if(send && result.data.submission_state === "DRAFT")await rawApi.post("/v1/actions/submit-all",{action_ids:[result.data.id]});return send;},onSuccess:async(send)=>{await refresh();setEditing(!send);setConfirmation(false);setNotice(send?"Instruction sent to Photon Legal.":"Draft saved. Send it when you are ready for Photon Legal to act.");},onError:()=>{}});
  const progress = useMutation({mutationFn:async(status:string)=>{if(!request)throw Error("Request unavailable");if(status==="DECLINED")await rawApi.post(`/v1/actions/${request.id}/resolve`,{status,note:responseNote.trim()});else await rawApi.patch(`/v1/actions/${request.id}/request-status`,{status});},onSuccess:async()=>{await refresh();setDeclining(false);setResponseNote("");setNotice("Request updated.");},onError:()=>{}});
  const requiredMissing = !template || (template.requires_countries && !selectedCountries.length) || (template.requires_note && !note.trim());
  const next = request?.status === "NEW" ? ["ACKNOWLEDGED","Acknowledge instruction"] : request?.status === "ACKNOWLEDGED" ? ["IN_PROGRESS","Start work"] : request?.status === "IN_PROGRESS" ? ["COMPLETED","Mark request completed"] : null;
  return <article aria-label="Selected event instruction">
    <header className="border-b border-pl-border pb-5"><h2 className="break-words text-xl font-semibold leading-tight">{row.title}</h2><p className="mt-3 text-sm text-pl-text-2">{actionDate(row.due_at)} · {deadline(row)}</p><p className="mt-4 break-words text-sm">{row.patent?.title || "Patent title not recorded"}</p><Link className="mt-2 inline-flex items-center gap-2 break-all text-xs text-pl-text-2 underline underline-offset-4" to={`/patents/${row.patent.id}`}>{row.patent.application_number || "View patent record"}<ArrowUpRight aria-hidden="true" className="h-3 w-3 shrink-0"/></Link></header>
    {notice && <p role="status" className="mt-4 text-sm">{notice}</p>}
    <section className="py-5"><h3 className="text-sm font-semibold">{state(row)}</h3><p className="mt-2 text-sm leading-relaxed text-pl-text-2">{ownership(row,operator)}</p></section>
    {request && (!editing || operator) && <section className="border-t border-pl-border py-5"><h3 className="text-sm font-semibold">Client instruction</h3><p className="mt-3 break-words text-base font-medium">{request.instruction || "Instruction not recorded"}</p>{request.selected_countries.length > 0 && <p className="mt-3 text-sm text-pl-text-2">Countries: {request.selected_countries.map(c=>countryNames.of(c)||c).join(", ")}</p>}{request.note && <details className="mt-4"><summary className="cursor-pointer text-sm">Client note</summary><p className="mt-3 whitespace-pre-wrap break-words text-sm text-pl-text-2">{request.note}</p></details>}{operator && <p className="mt-4 text-xs text-pl-text-2">Sent by {request.requested_by?.name || "Workspace Admin"} · {actionDate(request.requested_at)}</p>}{request.response_note && <p className="mt-4 whitespace-pre-wrap break-words text-sm text-pl-text-2">Photon Legal’s response: {request.response_note}</p>}</section>}
    {!operator && row.status !== "COMPLETED" && request?.status !== "COMPLETED" && (editing ? <form onSubmit={e=>{e.preventDefault();if(!requiredMissing)setConfirmation(true);}} className="border-t border-pl-border py-5">
      {templates.isLoading ? <p role="status" className="text-sm text-pl-text-2">Loading allowed instructions…</p> : templates.isError ? <><p role="alert" className="text-sm">Allowed instructions could not be loaded. Your choices are retained.</p><Button size="sm" variant="outline" className="mt-3" onClick={()=>templates.refetch()}>Reload instructions</Button></> : !templates.data?.length ? <><h3 className="text-sm font-semibold">Instruction options are not configured</h3><p className="mt-3 text-sm text-pl-text-2">Photon Legal needs to configure the options for this event. Contact your Case Owner before the deadline.</p></> : <>
      {!confirmation && <fieldset disabled={save.isPending}><legend className="text-sm font-semibold">Choose an instruction</legend><div className="mt-3 space-y-3">{templates.data.map(t=><label key={t.id} className="flex cursor-pointer items-start gap-3 rounded-sm border-b border-pl-border py-3"><input className="mt-1 accent-pl-ink" type="radio" name={`instruction-${row.id}`} value={t.id} checked={templateId===t.id} onChange={()=>{setTemplateId(t.id);save.reset();setNotice("");track("instruction_picked",{template_id:t.id,patent_id:row.patent.id});}}/><span className="min-w-0"><span className="block text-sm font-medium">{t.label}</span><span className="mt-1 block text-sm leading-relaxed text-pl-text-2">{t.description}</span></span></label>)}</div>
      {template?.requires_countries && <div className="mt-5"><Label htmlFor="instruction-country-search">Countries — choose at least one</Label><Input id="instruction-country-search" value={countrySearch} onChange={e=>setCountrySearch(e.target.value)} className={`mt-2 h-9 ${actionField}`} placeholder="Find a country"/><p className="mt-2 text-xs text-pl-text-2">{selectedCountries.length ? `Selected: ${selectedCountries.map(c=>countryNames.of(c)||c).join(", ")}` : "No countries selected."}</p><div tabIndex={0} aria-label="Available countries" className="mt-3 grid max-h-48 grid-cols-2 gap-3 overflow-y-auto py-2">{countries.filter(c=>`${c} ${countryNames.of(c)}`.toLowerCase().includes(countrySearch.toLowerCase())).map(c=><label key={c} className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1 accent-pl-ink" checked={selectedCountries.includes(c)} onChange={()=>setCountries(old=>old.includes(c)?old.filter(v=>v!==c):[...old,c])}/>{countryNames.of(c)||c}</label>)}</div></div>}
      {template && <div className="mt-5"><Label htmlFor="instruction-note">{template.requires_note ? "Reason — required" : "Note to Photon Legal — optional"}</Label><Textarea id="instruction-note" value={note} onChange={e=>setNote(e.target.value)} className={`mt-2 ${actionField}`} required={template.requires_note}/></div>}</fieldset>}
      {save.isError && <p role="alert" className="mt-4 text-sm">Instruction could not be saved or sent. Your choices are retained; try again.</p>}
      {confirmation ? <div ref={confirmRef} tabIndex={-1} className="rounded-sm focus-visible:outline-none"><p className="mb-4 text-base font-medium">{template?.label}</p>{template?.requires_countries && <p className="mb-4 text-sm text-pl-text-2">Countries: {selectedCountries.map(c=>countryNames.of(c)||c).join(", ")}</p>}{note && <details className="mb-4"><summary className="cursor-pointer text-sm">Note to Photon Legal</summary><p className="mt-2 whitespace-pre-wrap break-words text-sm text-pl-text-2">{note}</p></details>}<h3 className="text-sm font-semibold">Send this instruction to Photon Legal?</h3><p className="mt-2 text-sm text-pl-text-2">{request && request.submission_state !== "DRAFT" ? "This replaces your previous instruction and returns the request to Photon Legal for acknowledgment." : "Photon Legal will receive this instruction and own the next step. Other saved drafts will stay unsent."}</p><div className="mt-4 flex flex-wrap gap-3"><Button type="button" size="sm" className={actionPrimary} disabled={save.isPending} onClick={()=>{track("actions_submit_all_clicked");save.mutate(true);}}>{save.isPending ? "Sending instruction…" : "Send instruction"}</Button><Button type="button" size="sm" variant="outline" disabled={save.isPending} onClick={()=>setConfirmation(false)}>Keep editing</Button></div></div> : <div className="sticky bottom-0 mt-5 flex flex-wrap gap-3 border-t border-pl-border bg-pl-bg py-4"><Button size="sm" type="submit" className={actionPrimary} disabled={requiredMissing || save.isPending}>Review instruction to send</Button>{(!request || request.submission_state === "DRAFT") && <Button size="sm" type="button" variant="outline" disabled={requiredMissing || save.isPending} onClick={()=>save.mutate(false)}>{save.isPending ? "Saving draft…" : "Save draft"}</Button>}{request && request.submission_state !== "DRAFT" && <Button type="button" size="sm" variant="ghost" onClick={()=>{setEditing(false);setTemplateId(request.template_id||"");setCountries(request.selected_countries);setNote(request.note||"");}}>Cancel changes</Button>}</div>}
      </>}
    </form> : <Button size="sm" variant="outline" onClick={()=>{setEditing(true);setNotice("");}}>Update instruction</Button>)}
    {operator && request && <div className="sticky bottom-0 border-t border-pl-border bg-pl-bg py-4">{progress.isError && <p role="alert" className="mb-4 text-sm">Request could not be updated. Your response is retained; try again.</p>}{declining ? <form onSubmit={e=>{e.preventDefault();if(responseNote.trim())progress.mutate("DECLINED");}}><Label htmlFor="decline-note">Why is Photon Legal declining this request?</Label><Textarea id="decline-note" value={responseNote} onChange={e=>setResponseNote(e.target.value)} required className={`mt-3 ${actionField}`}/><p className="mt-3 text-sm text-pl-text-2">The Workspace Admin will receive this response and own the next step.</p><div className="mt-4 flex flex-wrap gap-3"><Button size="sm" type="submit" className={actionPrimary} disabled={!responseNote.trim() || progress.isPending}>{progress.isPending ? "Updating request…" : "Decline request"}</Button><Button size="sm" type="button" variant="outline" disabled={progress.isPending} onClick={()=>setDeclining(false)}>Keep request</Button></div></form> : next && <div className="flex flex-wrap gap-3"><Button size="sm" className={actionPrimary} disabled={progress.isPending} onClick={()=>progress.mutate(next[0])}>{progress.isPending ? "Updating request…" : next[1]}</Button><DropdownMenu><DropdownMenuTrigger asChild><Button size="sm" variant="outline" disabled={progress.isPending}>More <ChevronDown aria-hidden="true"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="bg-pl-bg text-pl-ink"><DropdownMenuItem onSelect={()=>setDeclining(true)}>Decline request…</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>}</div>}
  </article>;
}
